# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nicholas/studium/mathe/lgo/prog1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nicholas/studium/mathe/lgo/prog1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nicholas/studium/mathe/lgo/prog1/CMakeFiles /home/nicholas/studium/mathe/lgo/prog1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nicholas/studium/mathe/lgo/prog1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named prog1

# Build rule for target.
prog1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prog1
.PHONY : prog1

# fast build rule for target.
prog1/fast:
	$(MAKE) -f CMakeFiles/prog1.dir/build.make CMakeFiles/prog1.dir/build
.PHONY : prog1/fast

fourier_motzkin.o: fourier_motzkin.cpp.o

.PHONY : fourier_motzkin.o

# target to build an object file
fourier_motzkin.cpp.o:
	$(MAKE) -f CMakeFiles/prog1.dir/build.make CMakeFiles/prog1.dir/fourier_motzkin.cpp.o
.PHONY : fourier_motzkin.cpp.o

fourier_motzkin.i: fourier_motzkin.cpp.i

.PHONY : fourier_motzkin.i

# target to preprocess a source file
fourier_motzkin.cpp.i:
	$(MAKE) -f CMakeFiles/prog1.dir/build.make CMakeFiles/prog1.dir/fourier_motzkin.cpp.i
.PHONY : fourier_motzkin.cpp.i

fourier_motzkin.s: fourier_motzkin.cpp.s

.PHONY : fourier_motzkin.s

# target to generate assembly for a file
fourier_motzkin.cpp.s:
	$(MAKE) -f CMakeFiles/prog1.dir/build.make CMakeFiles/prog1.dir/fourier_motzkin.cpp.s
.PHONY : fourier_motzkin.cpp.s

ineq.o: ineq.cpp.o

.PHONY : ineq.o

# target to build an object file
ineq.cpp.o:
	$(MAKE) -f CMakeFiles/prog1.dir/build.make CMakeFiles/prog1.dir/ineq.cpp.o
.PHONY : ineq.cpp.o

ineq.i: ineq.cpp.i

.PHONY : ineq.i

# target to preprocess a source file
ineq.cpp.i:
	$(MAKE) -f CMakeFiles/prog1.dir/build.make CMakeFiles/prog1.dir/ineq.cpp.i
.PHONY : ineq.cpp.i

ineq.s: ineq.cpp.s

.PHONY : ineq.s

# target to generate assembly for a file
ineq.cpp.s:
	$(MAKE) -f CMakeFiles/prog1.dir/build.make CMakeFiles/prog1.dir/ineq.cpp.s
.PHONY : ineq.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/prog1.dir/build.make CMakeFiles/prog1.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/prog1.dir/build.make CMakeFiles/prog1.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/prog1.dir/build.make CMakeFiles/prog1.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... prog1"
	@echo "... edit_cache"
	@echo "... fourier_motzkin.o"
	@echo "... fourier_motzkin.i"
	@echo "... fourier_motzkin.s"
	@echo "... ineq.o"
	@echo "... ineq.i"
	@echo "... ineq.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

